version: '3'

services:
  database:
    image: mongo
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: tweet_classify

  messagery:
    image: rabbitmq:3.7-management
    ports:
      - 15672:15672
      - 5672:5672

  classifier:
    build: ./classifier
    env_file:
      - .env
    depends_on:
      - database
      - messagery
    volumes:
      - ./classifier:/classifier

  fetcher:
    build: ./fetcher
    env_file:
      - .env
    depends_on:
      - database
      - messagery
    volumes:
      - ./fetcher:/fetcher

  app:
    build: ./api
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080
