db.terms.insertOne({ term: '#apifirst' });
db.terms.insertOne({ term: '#devops' });
db.terms.insertOne({ term: '#cloudfirst' });
db.terms.insertOne({ term: '#microservices' });
db.terms.insertOne({ term: '#apigateway' });
db.terms.insertOne({ term: '#oauth' });
db.terms.insertOne({ term: '#swagger' });
db.terms.insertOne({ term: '#raml' });
db.terms.insertOne({ term: '#openapis' });
